name: CI pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14  # Adjust the version as needed

    - name: Install dependencies
      run: npm ci
      
    # - name: Run tests
    #   run: npm test

    # - name: Generate Code Coverage
    #   run: npm run coverage  # Assuming you have a script for running tests with coverage

    # - name: Upload Code Coverage Results
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: coverage
    #     path: coverage
