name: CI pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14 

    - name: Clear npm cache
      run: npm cache clean -f

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
